# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: "https://spiritedtechie.com"
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page/:num"

pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 6
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
  indexpage: "index"

# Collections
collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Spirited Techie"

category_dir: 'category'

analytics:
  google_analytics_id: ""

disqus:
  shortname: "" # Your disqus shortcode. leave this blank to disable comments globally

mailchimp:
  form_action_url: 

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: false 
  show_dark_mode_toggle_in_bottom: true # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
  show_dark_mode_toggle_in_mobile_menu: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode

colors:
  #light-mode colors
  primary: "#EC255A"
  primary_2: "#eed2d9"
  primary_text: "#f9fafb"
  background: "#ffffff"
  background_2: "#f6f6f6"
  background_3: "#f1f3f4"
  text: "#191a1a"
  text_2: "#555555"
  logo_text: "#191a1a"

  # dark-mode colors
  primary_dark: "#EC255A"
  primary_2_dark: "#eed2d9"
  primary_text_dark: "#f9fafb"
  background_dark: "#121418"
  background_2_dark: "#1d2026"
  background_3_dark: "#24272d"
  text_dark: "#F4F4F5"
  text_2_dark: "#D1D5DB"
  logo_text_dark: "#F4F4F5"

fonts:
  google_fonts: "https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Open+Sans:wght@300;400;500;600;700&display=swap"
  heading: "Lato"
  base: "Lato"
  monospace: "Lato"
  logo: "Lato"

logo:
  logo_image: assets/images/logo/logo.png
  logo_text: ""
  logo_image_mobile: assets/images/logo/logo-mobile.png
  logo_image_invert: assets/images/logo/logo-invert.png
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  logo_image_desktop_height: "27px"
  logo_image_desktop_width: "20px"
  logo_image_mobile_height: "27px"
  logo_image_mobile_width: "20px"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: false
  show_logo_text_on_mobile: false
  show_logo_text_on_desktop: true

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

header: 
  fixed: false

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  copyright_text: "© 2023 Spirited Techie"


